# This file was generated by GoReleaser. DO NOT EDIT.
cask "skill-review" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "742347a409cfdfe2890da05cc3e3877ba2291d16f63c2215630d8aebab6a4b26"
      url "https://github.com/O-Marsters-1997/skill-improver/releases/download/v#{version}/skill-improver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "587edb464320b235f23f543a132b3d101a90e99c7ca2792167b0b0e5f2ce440d"
      url "https://github.com/O-Marsters-1997/skill-improver/releases/download/v#{version}/skill-improver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88b497646868328c7609f8f517c4766c000e7a08ed6a7814c354a8fcbea14373"
      url "https://github.com/O-Marsters-1997/skill-improver/releases/download/v#{version}/skill-improver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa69a70463e3109cd71d2349589635dd9087ca8e7e714f1d4e1ba939e3d8ef23"
      url "https://github.com/O-Marsters-1997/skill-improver/releases/download/v#{version}/skill-improver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skill-review"
  desc "Review a SKILL.md in the browser, anchored to the source file"
  homepage "https://github.com/O-Marsters-1997/skill-improver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skill-review"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skill-review"]
    end
  end

  # No zap stanza required

end
