# This file was generated by GoReleaser. DO NOT EDIT.
cask "skill-review" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "af33decb1304a5ef017083620ad13118e3a5c163bc15c424c12e109ad3720e4b"
      url "https://github.com/O-Marsters-1997/skill-improver/releases/download/v#{version}/skill-improver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c5e2b838c59767270082c2f63362ea3f869a2a1dd969b623703292c1100ad2f"
      url "https://github.com/O-Marsters-1997/skill-improver/releases/download/v#{version}/skill-improver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1854da73a767b00461e445865bea7821ffab9ad7831e00ccafda9d7be24de97b"
      url "https://github.com/O-Marsters-1997/skill-improver/releases/download/v#{version}/skill-improver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "760ba3f2c537b9e3dfe41b7e698830c3765cf5c55fe54b3da945e93f93f2273b"
      url "https://github.com/O-Marsters-1997/skill-improver/releases/download/v#{version}/skill-improver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skill-review"
  desc "Review a SKILL.md in the browser, anchored to the source file"
  homepage "https://github.com/O-Marsters-1997/skill-improver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skill-review"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skill-review"]
    end
  end

  # No zap stanza required

end
