# This file was generated by GoReleaser. DO NOT EDIT.
cask "treepad" do
  version "0.3.36"

  on_macos do
    on_intel do
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
      sha256 "86ee809a1028c6362544bcf3d052d65e3ff32196584549a3a8f98ba6ff2eb145"
    end
    on_arm do
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
      sha256 "7bf574d6fbbc9c51918d7d0cc92d16c9548366e9c5c7c8d5261a821d464fbea9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_linux_amd64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
      sha256 "cb655e696f969c32485c1280d746e0563182f38d45dc602cbc9ad5a2af3dd003"
    end
    on_arm do
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_linux_arm64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
      sha256 "233f753b1f30b5166d8df807fbcfa53efbaa8ca0d5a698e253d0f6164d2c4d8c"
    end
  end

  name "treepad"
  desc "CLI for managing git worktrees"
  homepage "https://github.com/O-Marsters-1997/treepad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tp"]
  end

  # No zap stanza required

end
