# This file was generated by GoReleaser. DO NOT EDIT.
cask "treepad" do
  version "0.3.35"

  on_macos do
    on_intel do
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
      sha256 "a00c01ee3118280ef537f39865840e511170c698684c94179a124cb0a5b1f9df"
    end
    on_arm do
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
      sha256 "75d40dec41f00e4a0bcf59d1e95af345838815e6cad33beff2ac843420221529"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_linux_amd64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
      sha256 "9a0fd92c9376031864ed810a63dd0fc287d91386d42eb427270dddab20dd55d1"
    end
    on_arm do
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_linux_arm64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
      sha256 "4332ea87a7b856bb0ae5a5fdf4880e7d8fae679cb4f9834c6886da820e1d1454"
    end
  end

  name "treepad"
  desc "CLI for managing git worktrees"
  homepage "https://github.com/O-Marsters-1997/treepad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tp"]
  end

  # No zap stanza required

end
