# This file was generated by GoReleaser. DO NOT EDIT.
cask "treepad" do
  version "0.4.15"

  on_macos do
    on_intel do
      sha256 "1743e3c268cd39e91b5d758a03c80470c20a1bba0f0c6f20bd294ce4c8aa7db3"
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
    end
    on_arm do
      sha256 "3c330be2e3edcf6b34e1ffaa7cd464dc6daf48cd23d5d62d20819169358e7da0"
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
    end
  end

  on_linux do
    on_intel do
      sha256 "eea5d5a94d8732d550a848c7288c011da8ba5f7c920e57f61cd50d5164c10fa7"
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_linux_amd64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
    end
    on_arm do
      sha256 "e5c4b3149203abbbaf9be1c0faf3d74c23eb8426d1a2320c325d8cc3fd8065b7"
      url "https://github.com/O-Marsters-1997/treepad/releases/download/#{version}/treepad_#{version}_linux_arm64.tar.gz",
        verified: "github.com/O-Marsters-1997/treepad/"
    end
  end

  name "treepad"
  desc "CLI for managing git worktrees"
  homepage "https://github.com/O-Marsters-1997/treepad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tp"]
  end

  # No zap stanza required

end
